### ISSUE TITLE
Image select while nesting element 

### ISSUE THREAD

**Issue by VivekNitsan** [a-r-m-i-n/dce#94] opened 2023-12-04 05:38 UTC
Hello there I need help with this point.

```
<config>
	<type>group</type>
	<internal_type>db</internal_type>
	<appearance>
		<elementBrowserType>file</elementBrowserType>
		<elementBrowserAllowed>jpg, jpeg,png, gif</elementBrowserAllowed>
	</appearance>
	<allowed>sys_file</allowed>
	<size>5</size>
	<minitems>0</minitems>
	<maxitems>5</maxitems>
	<show_thumbs>1</show_thumbs>
</config>
```

Above Flexform is not working with TYPO3 v12 while nesting element and FAL is not working for nesting element it shows empty file selector

![image](https://github.com/a-r-m-i-n/dce/assets/97843751/d757a849-f0f8-4f20-b007-396950b4e12f)
  
Thanks in advance

**Comment by a-r-m-i-n** [comment] 2023-12-04 16:42
Duplicate of https://github.com/a-r-m-i-n/dce/issues/73#issuecomment-1695750224

**Closed as completed by a-r-m-i-n** 2023-12-04 16:42 UTC
Labels: bug
