### ISSUE TITLE
DCE public icon - one small error in the path will block complete backend DCE usage

### ISSUE THREAD

**Issue by daUhradone** [a-r-m-i-n/dce#93] opened 2023-11-28 22:37 UTC
It is nice that you can have now your public ions in an extension (sitepackage) EXT: and use SVGs.

But still, if you have a small typo or error in your path (tested on svg) the whole backend gets blocked an the only solution I found is to use phpmyadmin to correct the path in the database.

Later on I also saw that you can still delete the respective DCE in the list-view - but also not a good solution.

This is not very beginner friendly! They will spend hours and not find any solution.

It would be nice if the error could be catched and not the whole DCE backend be blocked.

THANKS!

**Comment by a-r-m-i-n** [comment] 2024-03-07 19:19
You could also edit the icon in the list module on root page. There, also all DCEs appear. Or which position in Backend do you mean?

**Comment by a-r-m-i-n** [comment] 2024-08-05 15:33
Closing this issue. I'm unable to reproduce this issue (in v12 or v13).

**Closed by a-r-m-i-n** 2024-08-05 15:33 UTC
Labels: enhancement
