### ISSUE TITLE
Error 503 when disabling a DCE content in mode page.

### ISSUE THREAD

**Issue by baden32** [a-r-m-i-n/dce#110] opened 2024-04-23 11:03 UTC
**Versions**
- DCE version: **2.9.5**
- TYPO3 version: **11.5.36**
- PHP version: **x8.2**
In composer mode.

Everytime I disable (switch off) a DCE in Page mode, I get the following error:

503
Oops, an error occurred!
T3\Dce\Domain\Repository\DceRepository::simulateContentElementSettings(): Argument #1 ($contentElementUid) must be of type int, null given, called in /home/clients/7e1212af22f8b93098f2ea07fad80c4d/sites/swisco.ch/swisco/public/typo3conf/ext/dce/Classes/Domain/Repository/DceRepository.php on line 722

If I switch off in List mode, no error occurs.

Could someone help me to solve this issue?

Regards,
Joël

**Comment by baden32** [comment] 2024-04-23 12:44
I made additional testing and can find more details in the typo3 logfile:

Tue, 23 Apr 2024 14:41:28 +0200 [WARNING] request="c4f545f328172" component="TYPO3.CMS.Core.Error.ErrorHandler": Core: Error handler (BE): PHP Warning: Trying to access array offset on value of type null in /home/clients/7e1212af22f8b93098f2ea07fad80c4d/sites/swisco.ch/swisco/public/typo3conf/ext/dce/Classes/Domain/Repository/DceRepository.php line 721 
Tue, 23 Apr 2024 14:41:28 +0200 [WARNING] request="c4f545f328172" component="TYPO3.CMS.Core.Error.ErrorHandler": Core: Error handler (BE): PHP Warning: Trying to access array offset on value of type null in /home/clients/7e1212af22f8b93098f2ea07fad80c4d/sites/swisco.ch/swisco/public/typo3conf/ext/dce/Classes/Domain/Repository/DceRepository.php line 722 
Tue, 23 Apr 2024 14:41:28 +0200 [CRITICAL] request="c4f545f328172" component="TYPO3.CMS.Core.Error.ProductionExceptionHandler": Core: Exception handler (WEB: BE): TypeError, code #0, file /home/clients/7e1212af22f8b93098f2ea07fad80c4d/sites/swisco.ch/swisco/public/typo3conf/ext/dce/Classes/Domain/Repository/DceRepository.php, line 735: T3\Dce\Domain\Repository\DceRepository::simulateContentElementSettings(): Argument #1 ($contentElementUid) must be of type int, null given, called in /home/clients/7e1212af22f8b93098f2ea07fad80c4d/sites/swisco.ch/swisco/public/typo3conf/ext/dce/Classes/Domain/Repository/DceRepository.php on line 722 - {"mode":"WEB","application_mode":"BE","exception_class":"TypeError","exception_code":0,"file":"/home/clients/7e1212af22f8b93098f2ea07fad80c4d/sites/swisco.ch/swisco/public/typo3conf/ext/dce/Classes/Domain/Repository/DceRepository.php","line":735,"message":"T3\\Dce\\Domain\\Repository\\DceRepository::simulateContentElementSettings(): Argument #1 ($contentElementUid) must be of type int, null given, called in /home/clients/7e1212af22f8b93098f2ea07fad80c4d/sites/swisco.ch/swisco/public/typo3conf/ext/dce/Classes/Domain/Repository/DceRepository.php on line 722","request_url":"https://swisco.ch/typo3/record/commit?token=--AnonymizedToken--&data[tt_content][1186][hidden]=1&redirect=%2Ftypo3%2Fmodule%2Fweb%2Flayout%3Ftoken%3D--AnonymizedToken--%26id%3D225","exception":null}

Hope it can help.
Regards
Joel

**Comment by a-r-m-i-n** [comment] 2024-08-05 12:31
Hi Joel,
thanks for reporting. I've tried to reproduce your issue, but I wasn't able to.

Instead I've recognized an error in system log, after disabling a content element based on DCE in page or list module:
> Core: Error handler (BE): PHP Warning: Undefined array key "t3_origuid" in /var/www/dce/Classes/Hooks/AfterSaveHook.php line 96

But I've also tested in latest version of DCE (in TYPO3 v13).

Because regular support of TYPO3 11 LTS is going to end soon, I won't fix it anymore for. I'm sorry. 
I'm going to close this issue.

---

But I want to help you.

It would be interesting to see the full stacktrace for this issue, to help you, to write a Composer patch instead.
The method "‎DceRepository::getDceInstance()" is called 5 times. I think two of those calls are probably responsible for your issue:

* Container Factory (Does the DCE you disable have DCE container feature enabled)?
* DceViewHelper (Do you have a custom backend preview template, using the DceViewHelper?)

**Closed by a-r-m-i-n** 2024-08-05 12:31 UTC
Labels: bug
