### ISSUE TITLE
TYPO3 FAL Image in section of a DCE

### ISSUE THREAD

**Issue by savinrajmb** [a-r-m-i-n/dce#83] opened 2023-09-28 03:39 UTC
**Versions**
- DCE version: 3.2
- TYPO3 version: 12.4.6
- PHP version: 8.1

This is the configuration for the image in dce for typo3 12 inside section.
In particular page when i add particular content element image uplaod option not showing.
![Capture](https://github.com/a-r-m-i-n/dce/assets/122771072/90656a7d-7825-4cc9-a68d-4279bccabfe7)
![dce](https://github.com/a-r-m-i-n/dce/assets/122771072/506c2f81-28ec-49e7-8435-29fa2f803b89)
![dce_720](https://github.com/a-r-m-i-n/dce/assets/122771072/253cf0d4-faf4-48d6-b3ea-e65ee751542d)

**Comment by a-r-m-i-n** [comment] 2023-09-30 12:45
Duplicate of https://github.com/a-r-m-i-n/dce/issues/73#issuecomment-1695750224

Avoid using sections!

**Closed by a-r-m-i-n** 2023-09-30 12:45 UTC
Labels: bug
