### ISSUE TITLE
Error when using DCE in BE context for install (i.e. upgrade wizard)

### ISSUE THREAD

**Issue by Oktopuce** [a-r-m-i-n/dce#107] opened 2024-04-03 16:20 UTC
**Versions**
- DCE version: **3.1.2**
- TYPO3 version: **12.4.13**
- PHP version: **8.2**

**Describe the bug**
When trying to upgrade with the **b13/container** extension using the updgrade wizard "**EXT:container: Migrate "container" sorting**", there is an error:

(1/1) TypeError
TYPO3\CMS\Core\Http\ApplicationType::fromRequest(): Argument #1 ($request) must be of type Psr\Http\Message\ServerRequestInterface, null given, called in /data/site/sdl_v11/vendor/t3/dce/Classes/Components/TemplateRenderer/StandaloneViewFactory.php on line 143

This error appears because test for the context is like this:

`if (ApplicationType::fromRequest($GLOBALS['TYPO3_REQUEST'])->isFrontend()) {`

while in that case it should be something like that:

`if (!isset($_REQUEST['install']) && ApplicationType::fromRequest($GLOBALS['TYPO3_REQUEST'])->isFrontend()) {`

have a look at this screen capture:

![Erreur container Upgrade Wizard](https://github.com/a-r-m-i-n/dce/assets/7236405/9007ef13-6673-4672-b767-67a3e4a39cec)

There is also another error in **TypoScript.php**, method **getTypoScriptSetupArray()** because "**$GLOBALS['TYPO3_REQUEST']**" is not always set - same context as above - a test should be done like that:

```
public function getTypoScriptSetupArray(): ?array
{
    if (!$GLOBALS['TYPO3_REQUEST']) {
        return null;
    }

    /** @var FrontendTypoScript|null $frontendTypoScript */
   $frontendTypoScript = $GLOBALS['TYPO3_REQUEST']->getAttribute('frontend.typoscript');
```

See also : [https://github.com/b13/container/issues/489](url)

**Comment by a-r-m-i-n** [comment] 2024-04-03 20:52
Duplicate of #105

Please update to latest DCE version 3.1.3, there this issue is already fixed.

**Closed by a-r-m-i-n** 2024-04-03 20:52 UTC
Labels: bug
