### ISSUE TITLE
No Image Record Selection in Section

### ISSUE THREAD

**Issue by MalathDaThon** [a-r-m-i-n/dce#112] opened 2024-04-26 07:52 UTC
DCE version: 3.1.3
TYPO3 version: 12.4.13
PHP version: 8.2

Until V12 i was using the following code for inserting images in section, it worked perfectly:

```
<config>
        <type>group</type>
	<internal_type>db</internal_type>
	<appearance>
		<elementBrowserType>file</elementBrowserType>
		<elementBrowserAllowed>jpg,jpeg,png</elementBrowserAllowed>
	</appearance>
	<allowed>sys_file</allowed>
	<size>5</size>
	<minitems>0</minitems>
	<maxitems>1</maxitems>
	<show_thumbs>1</show_thumbs>
	<dce_load_schema>1</dce_load_schema>
	<dce_get_fal_objects>1</dce_get_fal_objects>
</config>
``` 

In v12 i cant get a working image selection box in editing mode.
It just opens an empty record selection window. 

I know appearance is depricated in v12, but even removing the apperance part does not solve the problem.
Also setting the internal_type to file wont work.

Can u help me figure out how to get it back to work?

Thank you :)

**Comment by a-r-m-i-n** [comment] 2024-04-26 18:41
Duplicate of #73

**Closed by a-r-m-i-n** 2024-04-26 18:41 UTC
Labels: Support
